[package]
name = "wasm-test"
version = "0.1.0"
authors = ["petamoriken <moriken@kimamass.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
lewton = "0.9.3"
wee_alloc = "0.4.2"
hound = "3.4.0"
